build:
  commands:
    - |
      bash -euo pipefail -c '
        SHA_TAG="$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | cut -c1-7)"
        IMAGE_FULL="$DOCKER_USER/$IMAGE_NAME:$IMAGE_TAG"
        IMAGE_SHA="$DOCKER_USER/$IMAGE_NAME:$SHA_TAG"

        echo "Building $IMAGE_FULL"
        docker build -t "$IMAGE_FULL" .
        docker tag "$IMAGE_FULL" "$IMAGE_SHA"

        echo "Pushing tags: latest and $SHA_TAG"
        docker push "$IMAGE_FULL"
        docker push "$IMAGE_SHA"
      '
